[package]
name = "qcext-server"
version = "0.1.0"
authors = ["Alexander Krivács Schrøder <alexschrod@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
futures = "0.3"
anyhow = "1.0"
pretty_env_logger = "0.4"
dotenv = "0.15"
once_cell = "1.4"
sqlx = { version="0.5", features=[
	"runtime-tokio-rustls",
	"mysql",
	"macros",
	"migrate",
	"uuid",
	"chrono",
] }
serde = "1"
