[package]
name = "qcext-server"
version = "0.1.0"
authors = ["Alexander Krivács Schrøder <alexschrod@gmail.com>"]
edition = "2018"
default-run = "qcext-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
actix-http = "3.0.0-beta.8"
futures = "0.3"
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
dotenv = "0.15"
once_cell = "1.8"
sqlx = { version = "0.5", features = [
    "runtime-tokio-native-tls",
    "mysql",
    "macros",
    "migrate",
    "uuid",
    "chrono",
] }
serde = "1"
uuid = { version = "0.8", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bitflags = "1.2"
tokio = "1.8"
reqwest = "0.11"
scraper = "0.12"
ego-tree = "0.6"
regex = "1.5"
const_format = "0.2"
chrono-tz = "0.5"
ilyvion-util = { version = "*", path = "../ilyvion-util" }
actix-web-grants = "3.0.0-beta.2"
serde_json = "1.0.64"
