[package]
name = "qcext-server"
version = "0.1.0"
authors = ["Alexander Krivács Schrøder <alexschrod@gmail.com>"]
edition = "2021"
default-run = "qcext-server"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "./database" }
shared = { path = "./shared" }

actix-files = "0.6.0-beta.7"
actix-http = "3.2"
actix-multipart = "0.4.0-beta.6"
actix-web = "4.1"
actix-web-grants = "3.0.0-beta.3"
anyhow = "1.0"
arc-swap = "1.5"
bitflags = "1.3"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.6"
const_format = "0.2"
crc32c = "0.6"
dotenv = "0.15"
ego-tree = "0.6"
futures = "0.3"
ilyvion-util = { version = "0.8", features = ["chrono"] }
log = "0.4"
once_cell = "1.8"
parse-display = "0.6"
pretty_env_logger = "0.4"
rand = "0.8"
regex = "1.5"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.13"
semval = "0.4"
serde = "1.0"
serde_json = "1.0"
tokio = "1.12"
uuid = { version = "1.1", features = ["serde"] }

[workspace]
members = ["database", "shared"]
