[package]
name = "qcext-server"
version = "0.1.0"
authors = ["Alexander Krivács Schrøder <alexschrod@gmail.com>"]
edition = "2018"
default-run = "qcext-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.9"
actix-http = "3.0.0-beta.9"
futures = "0.3"
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
dotenv = "0.15"
once_cell = "1.8"
sqlx = { version = "0.5", features = [
    "runtime-tokio-native-tls",
    "mysql",
    "macros",
    "migrate",
    "uuid",
    "chrono",
    "offline",
] }
serde = "1.0"
uuid = { version = "0.8", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bitflags = "1.3"
tokio = "1.12"
reqwest = "0.11"
scraper = "0.12"
ego-tree = "0.6"
regex = "1.5"
const_format = "0.2"
chrono-tz = "0.6"
ilyvion-util = "0.5"
actix-web-grants = { version = "3.0.0-beta.2", git = "https://github.com/DDtKey/actix-web-grants.git", rev = "b032b5bd5107bc7eae57edd7199e228143496896" } #"3.0.0-beta.2"
serde_json = "1.0"
actix-multipart = "0.4.0-beta.6"
crc32c = "0.6"
actix-files = "0.6.0-beta.7"
