[package]
name = "qcext-server"
version = "0.1.0"
authors = ["Alexander Krivács Schrøder <alexschrod@gmail.com>"]
edition = "2021"
default-run = "qcext-server"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1"
actix-http = "3.2"
arc-swap = "1.5"
futures = "0.3"
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
dotenv = "0.15"
once_cell = "1.8"
serde = "1.0"
uuid = { version = "1.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bitflags = "1.3"
tokio = "1.24"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.13"
ego-tree = "0.6"
regex = "1.5"
const_format = "0.2"
chrono-tz = "0.6"
ilyvion-util = { version = "0.8", features = ["chrono"] }
actix-web-grants = "3.0.0-beta.3"
serde_json = "1.0"
actix-multipart = "0.4.0-beta.6"
crc32c = "0.6"
actix-files = "0.6.0-beta.7"
semval = "0.4"
parse-display = "0.6"
rand = "0.8"
shared = { path = "./shared" }
database = { path = "./database" }

[workspace]
members = ["database", "shared"]
