// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCExtensions.Domain.Entities;
using QCExtensions.Server.Models;

namespace QCExtensions.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181218063347_MissingFeatureFlags")]
    partial class MissingFeatureFlags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QCExtensions.Server.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<bool>("HasNoCast");

                    b.Property<bool>("HasNoLocation");

                    b.Property<bool>("HasNoStoryline");

                    b.Property<bool>("HasNoTagline");

                    b.Property<bool>("HasNoTitle");

                    b.Property<bool>("IsAccuratePublishDate")
                        .HasColumnName("isAccuratePublishDate");

                    b.Property<bool>("IsGuestComic")
                        .HasColumnName("isGuestComic");

                    b.Property<bool>("IsNonCanon")
                        .HasColumnName("isNonCanon");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnName("publishDate");

                    b.Property<string>("Tagline")
                        .HasColumnName("tagline")
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("comic");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnName("color")
                        .HasMaxLength(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnName("shortName")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("CRC32CHash");

                    b.Property<byte[]>("Image")
                        .IsRequired();

                    b.Property<int>("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<DateTime>("DateTime");

                    b.Property<Guid>("UserToken");

                    b.HasKey("Id");

                    b.HasIndex("UserToken");

                    b.ToTable("log_entry");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.News", b =>
                {
                    b.Property<int>("Comic")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comic");

                    b.Property<bool>("IsLocked")
                        .HasColumnName("isLocked");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnName("lastUpdated");

                    b.Property<string>("NewsText")
                        .IsRequired()
                        .HasColumnName("news");

                    b.Property<double>("UpdateFactor")
                        .HasColumnName("updateFactor");

                    b.HasKey("Comic");

                    b.ToTable("news");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Occurrence", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnName("comic_id");

                    b.Property<int>("ItemId")
                        .HasColumnName("items_id");

                    b.HasKey("ComicId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("occurences");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("token");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Comic", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.News", "News")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCExtensions.Server.Models.ItemImage", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCExtensions.Server.Models.LogEntry", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.Token", "Token")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserToken")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Occurrence", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.Comic", "Comic")
                        .WithMany("Occurrences")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QCExtensions.Server.Models.Item", "Item")
                        .WithMany("Occurrences")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
