// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCExtensions.Server.Models;

namespace QCExtensions.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QCExtensions.Server.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<bool>("IsAccuratePublishDate")
                        .HasColumnName("isAccuratePublishDate");

                    b.Property<bool>("IsGuestComic")
                        .HasColumnName("isGuestComic");

                    b.Property<bool>("IsNonCanon")
                        .HasColumnName("isNonCanon");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnName("publishDate");

                    b.Property<string>("Tagline")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("comic");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnName("shortName");

                    b.Property<string>("Type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Action");

                    b.Property<DateTime>("DateTime");

                    b.Property<Guid>("UserToken");

                    b.HasKey("Id");

                    b.HasIndex("UserToken");

                    b.ToTable("log_entry");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.News", b =>
                {
                    b.Property<int>("Comic")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comic");

                    b.Property<bool>("IsLocked")
                        .HasColumnName("isLocked");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnName("lastUpdated");

                    b.Property<string>("NewsText")
                        .HasColumnName("news");

                    b.Property<double>("UpdateFactor")
                        .HasColumnName("updateFactor");

                    b.HasKey("Comic");

                    b.ToTable("news");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Occurrences", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnName("comic_id");

                    b.Property<int>("ItemId")
                        .HasColumnName("items_id");

                    b.HasKey("ComicId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("occurences");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Identifier");

                    b.HasKey("Id");

                    b.ToTable("token");
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Comic", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.News", "News")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCExtensions.Server.Models.LogEntry", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.Token", "Token")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserToken")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QCExtensions.Server.Models.Occurrences", b =>
                {
                    b.HasOne("QCExtensions.Server.Models.Comic", "Comic")
                        .WithMany("Occurrences")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QCExtensions.Server.Models.Item", "Item")
                        .WithMany("Occurrences")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
