name: Promote Staging to Production

on:
    workflow_dispatch:

jobs:
    promote:
        runs-on: ubuntu-latest
        steps:
            - uses: ilyvion-contrib/ci-utils/get-latest-deployment@main
              id: staging
              with:
                  environment: staging

            - uses: ilyvion-contrib/ci-utils/create-deployment@main
              id: deployment
              with:
                  ref: ${{ steps.staging.outputs.ref }}
                  sha: ${{ steps.staging.outputs.sha }}
                  environment: 'production'

            - uses: ilyvion-contrib/ci-utils/setup-ssh@main
              with:
                  ssh_known_hosts: ${{ secrets.deploy_known_hosts }}
                  ssh_private_key: ${{ secrets.deploy_key }}
                  ssh_host: ${{ secrets.deploy_target }}
                  ssh_port: ${{ secrets.deploy_port }}

            - name: Trigger promote script on server
              run: |
                  ssh -i ~/.ssh/id -p ${{ secrets.deploy_port }} \
                    ${{ secrets.deploy_user }}@${{ secrets.deploy_target }} \
                    'cd ~/docker/questionablextensions/; sudo promote-staging-to-prod.sh'

            - uses: ilyvion-contrib/ci-utils/update-deployment-status@main
              if: success()
              with:
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
                  state: success

            - uses: ilyvion-contrib/ci-utils/update-deployment-status@main
              if: failure()
              with:
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
                  state: failure
