name: Build and Deploy

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4

            - uses: ilyvion-contrib/container-ci-build@main
              with:
                image: questionablextensions

            - name: Upload artifact
              if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: questionablextensions-tar
                  path: questionablextensions.tar

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: questionablextensions-tar

            - uses: ilyvion-contrib/container-ci-deploy@main
              with:
                ssh_known_hosts: ${{ secrets.deploy_known_hosts }}
                ssh_private_key: ${{ secrets.deploy_key }}
                ssh_user: ${{ secrets.deploy_user }}
                ssh_host: ${{ secrets.deploy_target }}
                ssh_port: ${{ secrets.deploy_port }}
                image: questionablextensions
