name: Build and Deploy

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t qcext-server .

            - name: Save Docker image
              run: docker save -o qcext-server.tar qcext-server

            - name: Compress Docker image
              run: bzip2 -z qcext-server.tar

            - name: Deploy
              run: docker-compose run deploy
              env:
                  DEPLOY_KEY: ${{ secrets.deploy_key }}
                  DEPLOY_TARGET: ${{ secrets.deploy_target }}
                  DEPLOY_USER: ${{ secrets.deploy_user }}
